"""add password_changed_at to user table

Revision ID: 24bc7a3d728a
Revises: 188b71188b84
Create Date: 2026-09-28 12:54:07.181675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24bc7a3d728a'
down_revision: Union[str, Sequence[str], None] = '188b71188b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user-table', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user-table', 'password_changed_at')
    # ### end Alembic commands ###
